import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./providers/providers";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/[...nextauth]/route";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
       <Providers session={session}>
         <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  )
}
